### ISSUE TITLE
error: expected: insn.id() == ARM64_INS_BL

### ISSUE THREAD

**Issue by spr234** [worawit/blutter#11]
I am getting following error

Dart version: 3.1.0, Snapshot: 7dbbeeb8ef7b91338640dca3927636de, Target: android arm64
libapp is loaded at 0x1cb1b260000
Dart heap at 0x1cc00000000
Analyzing the application
at ..\..\src\CodeAnalyzer_arm64.cpp: 984: error: expected: insn.id() == ARM64_INS_BL

I am using Windows

also tried on debian trixie, same error 

How can I fix that?

**Comment by worawit** [comment]
I guess it is an unexpected generated code pattern from Dart compiler.

I pushed a patch to not stop the program if an error occurs in analysis step.
You can rerun with "--rebuild" option. An error is still printed.
Also, please give me an error message with printed assembly. I might be able to fix a bug.

**Comment by spr234** [comment]
Here you go

`
art version: 3.1.0, Snapshot: 7dbbeeb8ef7b91338640dca3927636de, Target: android arm64
-- Configuring done (0.1s)
-- Generating done (0.0s)
-- Build files have been written to: /home/trixie/blutter/build/blutter_dartvm3.1.0_android_arm64
[10/10] Linking CXX executable blutter_dartvm3.1.0_android_arm64
-- Install configuration: "Release"
-- Installing: /home/trixie/blutter/blutter/../bin/blutter_dartvm3.1.0_android_arm64
libapp is loaded at 0x7f9b91000000
Dart heap at 0x7f9a00000000
Analyzing the application
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e3508: ldurb w17, [x0, #-1]
    0x8e350c: and x16, x17, x16, lsr #2
    0x8e3510: tst x16, x28, lsr #32
    0x8e3514: b.eq #0x8e3520
  * 0x8e3518: ldr x30, [x26, #0x5f8]
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e3508: ldurb w17, [x0, #-1]
    0x8e350c: and x16, x17, x16, lsr #2
    0x8e3510: tst x16, x28, lsr #32
    0x8e3514: b.eq #0x8e3520
  * 0x8e3518: ldr x30, [x26, #0x5f8]
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e35bc: ldurb w17, [x0, #-1]
    0x8e35c0: and x16, x17, x16, lsr #2
    0x8e35c4: tst x16, x28, lsr #32
    0x8e35c8: b.eq #0x8e35d4
  * 0x8e35cc: ldr x30, [x26, #0x5f0]
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e35bc: ldurb w17, [x0, #-1]
    0x8e35c0: and x16, x17, x16, lsr #2
    0x8e35c4: tst x16, x28, lsr #32
    0x8e35c8: b.eq #0x8e35d4
  * 0x8e35cc: ldr x30, [x26, #0x5f0]
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e3610: ldurb w17, [x0, #-1]
    0x8e3614: and x16, x17, x16, lsr #2
    0x8e3618: tst x16, x28, lsr #32
    0x8e361c: b.eq #0x8e3628
  * 0x8e3620: ldr x30, [x26, #0x5f8]
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e3610: ldurb w17, [x0, #-1]
    0x8e3614: and x16, x17, x16, lsr #2
    0x8e3618: tst x16, x28, lsr #32
    0x8e361c: b.eq #0x8e3628
  * 0x8e3620: ldr x30, [x26, #0x5f8]
Analysis error at line 737 `ILResult FunctionAnalyzer::processLoadFieldTableInstr(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e3654: ldr x16, [x27, #0x38]
    0x8e3658: cmp w0, w16
    0x8e365c: b.ne #0x8e3674
    0x8e3660: ldr x2, [x27, #0x900]
  * 0x8e3664: add x24, x27, #0xc, lsl #12
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e36a8: ldurb w17, [x0, #-1]
    0x8e36ac: and x16, x17, x16, lsr #2
    0x8e36b0: tst x16, x28, lsr #32
    0x8e36b4: b.eq #0x8e36c0
  * 0x8e36b8: ldr x30, [x26, #0x600]
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e36a8: ldurb w17, [x0, #-1]
    0x8e36ac: and x16, x17, x16, lsr #2
    0x8e36b0: tst x16, x28, lsr #32
    0x8e36b4: b.eq #0x8e36c0
  * 0x8e36b8: ldr x30, [x26, #0x600]
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e36ec: ldurb w17, [x0, #-1]
    0x8e36f0: and x16, x17, x16, lsr #2
    0x8e36f4: tst x16, x28, lsr #32
    0x8e36f8: b.eq #0x8e3704
  * 0x8e36fc: ldr x30, [x26, #0x600]
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e36ec: ldurb w17, [x0, #-1]
    0x8e36f0: and x16, x17, x16, lsr #2
    0x8e36f4: tst x16, x28, lsr #32
    0x8e36f8: b.eq #0x8e3704
  * 0x8e36fc: ldr x30, [x26, #0x600]
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e377c: ldurb w17, [x0, #-1]
    0x8e3780: and x16, x17, x16, lsr #2
    0x8e3784: tst x16, x28, lsr #32
    0x8e3788: b.eq #0x8e3794
  * 0x8e378c: ldr x30, [x26, #0x5f0]
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e377c: ldurb w17, [x0, #-1]
    0x8e3780: and x16, x17, x16, lsr #2
    0x8e3784: tst x16, x28, lsr #32
    0x8e3788: b.eq #0x8e3794
  * 0x8e378c: ldr x30, [x26, #0x5f0]
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e37ac: ldurb w17, [x0, #-1]
    0x8e37b0: and x16, x17, x16, lsr #2
    0x8e37b4: tst x16, x28, lsr #32
    0x8e37b8: b.eq #0x8e37c4
  * 0x8e37bc: ldr x30, [x26, #0x5f0]
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e37ac: ldurb w17, [x0, #-1]
    0x8e37b0: and x16, x17, x16, lsr #2
    0x8e37b4: tst x16, x28, lsr #32
    0x8e37b8: b.eq #0x8e37c4
  * 0x8e37bc: ldr x30, [x26, #0x5f0]
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e37d4: ldurb w17, [x0, #-1]
    0x8e37d8: and x16, x17, x16, lsr #2
    0x8e37dc: tst x16, x28, lsr #32
    0x8e37e0: b.eq #0x8e37ec
  * 0x8e37e4: ldr x30, [x26, #0x5f0]
Analysis error at line 1301 `ILWBResult FunctionAnalyzer::processWriteBarrier(AsmInstruction)`: insn.id() == ARM64_INS_BL
    0x8e37d4: ldurb w17, [x0, #-1]
    0x8e37d8: and x16, x17, x16, lsr #2
    0x8e37dc: tst x16, x28, lsr #32
    0x8e37e0: b.eq #0x8e37ec
  * 0x8e37e4: ldr x30, [x26, #0x5f0]
Dumping Object Pool
Generating application assemblies
Generating Frida script
`

**Comment by worawit** [comment]
Committed a fix.

I have no full assembly to check. So, it might be wrong.
If there is still an error, can you send me a library?

**Comment by spr234** [comment]
I am still getting

Analysis error at line 752 `ILResult FunctionAnalyzer::processLoadFieldTableInstr(AsmInstruction)`: insn.id() == ARM64_INS_LDR
    0x8e365c: b.ne #0x8e3674
    0x8e3660: ldr x2, [x27, #0x900]
    0x8e3664: add x24, x27, #0xc, lsl #12
    0x8e3668: ldr x24, [x24, #0x660]
  * 0x8e366c: ldur x30, [x24, #7]
    0x8e3670: blr x30


Where can I send you library?

**Comment by worawit** [comment]
I guess you don't have to send me a library anymore.
Just fixed the last error. Thanks for a  bug report.

**Comment by spr234** [comment]
Yup, No more error
Thankyou for making such tool.
