### ISSUE TITLE
SIGSEGV issue on dart v3.5.3

### ISSUE THREAD

**Issue by mragonias** [worawit/blutter#113]
[3.5.3_issue_lib.zip](https://github.com/user-attachments/files/17690724/3.5.3_issue_lib.zip)

![Captura de pantalla 2024-11-08 162838](https://github.com/user-attachments/assets/60538b32-79f7-4ed1-a22e-786873dd9b98)

**Comment by worawit** [comment]
try the latest commit. it should work fine with your binary.

**Comment by mragonias** [comment]
> try the latest commit. it should work fine with your binary.

Thanks again!

**Comment by FlutterGenerator** [comment]
Hi brother, I'm waiting for a response fix to armeabi-v7a

**Comment by FlutterGenerator** [comment]
Plz update armeabi-v7a @worawit

**Comment by FlutterGenerator** [comment]
Plz update @worawit 
![IMG_20241117_225019_545](https://github.com/user-attachments/assets/c846a446-de89-47fb-a0d5-87270d421389)

**Comment by FlutterGenerator** [comment]
u0_a511@localhost ~> cd blutter && python3 blutter.py /storage/emulated/0/MT2/apks/armeabi-v7a/ /storage/emulated/0/MT2/apks/out_dir
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/blutter/blutter.py", line 229, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "/data/data/com.termux/files/home/blutter/blutter.py", line 211, in main
    main2(libapp_file, libflutter_file, outdir, rebuild_blutter, create_vs_sln, no_analysis)
  File "/data/data/com.termux/files/home/blutter/blutter.py", line 200, in main2
    dart_info = get_dart_lib_info(libapp_path, libflutter_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/blutter/blutter.py", line 151, in get_dart_lib_info
    dart_version, snapshot_hash, flags, arch, os_name = extract_dart_info(libapp_path, libflutter_path)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/blutter/extract_dart_info.py", line 110, in extract_dart_info
    engine_ids, dart_version, arch, os_name = extract_libflutter_info(libflutter_file)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/blutter/extract_dart_info.py", line 38, in extract_libflutter_info
    assert False, f"Unsupport architecture: {elf.header.e_machine}"
           ^^^^^
AssertionError: Unsupport architecture: EM_ARM
u0_a511@localhost ~/blutter (main) [1]>


Plz update @worawit 
![Screenshot_20241117-225736_Termux](https://github.com/user-attachments/assets/814ea9aa-d32e-4237-ab4a-365b8d07ba8c)

**Comment by FlutterGenerator** [comment]
Plz update android brother plz termux Mobile
@worawit

**Comment by mragonias** [comment]
> Plz update android brother plz termux Mobile @worawit

https://github.com/worawit/blutter/issues/31#issuecomment-1893775861

Stop spamming please

**Comment by daohx2002** [comment]
> try the latest commit. it should work fine with your binary.

how did you fix it, i have the same error?

**Comment by daohx2002** [comment]
@mragonias help me
