### ISSUE TITLE
dartvm3.5.4 Command '['ninja']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by debuggerfool** [worawit/blutter#116]
### My Environment: Python 3.12.3 + Visual Studio 2019

`python blutter.py ./arm64 ./output -- ./arm64 contains libapp.so and libflutter.so`

> Here are their compressed original files:  [arm64.zip](https://github.com/user-attachments/files/17797186/arm64.zip)

### All Process Output:
Dart version: 3.5.4, Snapshot: 80a49c7111088100a233b2ae788e1f48, Target: android arm64
flags: product no-code_comments dwarf_stack_traces_mode dedup_instructions no-tsan no-msan arm64 android compressed-pointers
Cloning into 'C:\Users\cpp\Desktop\ftdcp\blutterhome\dartsdk\v3.5.4'...
remote: Enumerating objects: 2434, done.
remote: Counting objects: 100% (2434/2434), done.
remote: Compressing objects: 100% (1965/1965), done.
remote: Total 2434 (delta 40), reused 1399 (delta 29), pack-reused 0 (from 0)
Receiving objects: 100% (2434/2434), 1.29 MiB | 4.54 MiB/s, done.
Resolving deltas: 100% (40/40), done.
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 24 (delta 0), reused 7 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (24/24), 147.04 KiB | 63.00 KiB/s, done.
Updating files: 100% (24/24), done.
remote: Enumerating objects: 2884, done.
remote: Counting objects: 100% (2884/2884), done.
remote: Compressing objects: 100% (2406/2406), done.
remote: Total 2884 (delta 527), reused 1218 (delta 435), pack-reused 0 (from 0)
Receiving objects: 100% (2884/2884), 8.54 MiB | 84.00 KiB/s, done.
Resolving deltas: 100% (527/527), done.
Updating files: 100% (3261/3261), done.
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/cpp/Desktop/ftdcp/blutterhome/build/dartvm3.5.4_android_arm64
[1/264] Building CXX object CMakeFiles\dartvm3.5.4_android_arm64.dir\runtime\vm\bootstrap_natives.cc.obj

> FAILED: CMakeFiles/dartvm3.5.4_android_arm64.dir/runtime/vm/bootstrap_natives.cc.obj
E:\MS2019\IDE\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe  /nologo /TP -DDART_COMPRESSED_POINTERS -DDART_PRECOMPILED_RUNTIME -DDART_TARGET_OS_ANDROID -DDART_TARGET_OS_WINDOWS_UWP -DEXCLUDE_CFE_AND_KERNEL_PLATFORM -DNDEBUG -DPRODUCT -DTARGET_ARCH_ARM64 -DU_USING_ICU_NAMESPACE=0 -D_HAS_EXCEPTIONS=0 -IC:\Users\cpp\Desktop\ftdcp\blutterhome\dartsdk\v3.5.4\runtime -IE:\anacondahome\Library\include /DWIN32 /D_WINDOWS  /O2 /Ob2 /DNDEBUG -MD /Oy /GR- /EHs-c- -std:c++17 /showIncludes /FoCMakeFiles\dartvm3.5.4_android_arm64.dir\runtime\vm\bootstrap_natives.cc.obj /FdCMakeFiles\dartvm3.5.4_android_arm64.dir\dartvm3.5.4_android_arm64.pdb /FS -c C:\Users\cpp\Desktop\ftdcp\blutterhome\dartsdk\v3.5.4\runtime\vm\bootstrap_natives.cc

E:\MS2019\IDE\VC\Tools\MSVC\14.29.30133\include\xkeycheck.h(53): warning C4005: 'bool': macro redefinition
E:\anacondahome\Library\include\stdbool.h(9): note: see previous definition of 'bool'
E:\MS2019\IDE\VC\Tools\MSVC\14.29.30133\include\xkeycheck.h(55): fatal error C1189: #error:  The C++ Standard Library forbids macroizing the keyword "bool". Enable warning C4005 to find the forbidden define.
[14/264] Building CXX object CMakeFiles\dartvm3.5.4_android_arm64.dir\runtime\vm\app_snapshot.cc.obj
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
    &emsp;&emsp;&emsp;File "C:\Users\cpp\Desktop\ftdcp\blutterhome\blutter.py", line 229, in <module>
      &emsp;&emsp;main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
    &emsp;&emsp;&emsp;File "C:\Users\cpp\Desktop\ftdcp\blutterhome\blutter.py", line 211, in main
      &emsp;&emsp;main2(libapp_file, libflutter_file, outdir, rebuild_blutter, create_vs_sln, no_analysis)
    &emsp;&emsp;&emsp;File "C:\Users\cpp\Desktop\ftdcp\blutterhome\blutter.py", line 202, in main2
      &emsp;&emsp;build_and_run(input)
    &emsp;&emsp;&emsp;File "C:\Users\cpp\Desktop\ftdcp\blutterhome\blutter.py", line 168, in build_and_run
      &emsp;&emsp;fetch_and_build(input.dart_info)
    &emsp;&emsp;&emsp;File "C:\Users\cpp\Desktop\ftdcp\blutterhome\dartvm_fetch_build.py", line 135, in fetch_and_build
      &emsp;&emsp;cmake_dart(info, outdir)
    &emsp;&emsp;&emsp;File "C:\Users\cpp\Desktop\ftdcp\blutterhome\dartvm_fetch_build.py", line 130, in cmake_dart
      &emsp;&emsp;subprocess.run([NINJA_CMD], cwd=builddir, check=True)
    &emsp;&emsp;&emsp;File "E:\anacondahome\Lib\subprocess.py", line 571, in run
      raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja']' returned non-zero exit status 1.

### Try Manually Ninja Bulid:

>cd     \build\dartvm3.5.4_android_arm64 and exectue ninja.

### Process Output:

[1/202] Building CXX object CMakeFiles\dartvm3.5.4_android_arm64.dir\runtime\vm\dart_api_state.cc.obj

> FAILED: CMakeFiles/dartvm3.5.4_android_arm64.dir/runtime/vm/dart_api_state.cc.obj
E:\MS2019\IDE\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe  /nologo /TP -DDART_COMPRESSED_POINTERS -DDART_PRECOMPILED_RUNTIME -DDART_TARGET_OS_ANDROID -DDART_TARGET_OS_WINDOWS_UWP -DEXCLUDE_CFE_AND_KERNEL_PLATFORM -DNDEBUG -DPRODUCT -DTARGET_ARCH_ARM64 -DU_USING_ICU_NAMESPACE=0 -D_HAS_EXCEPTIONS=0 -IC:\Users\cpp\Desktop\ftdcp\blutterhome\dartsdk\v3.5.4\runtime -IE:\anacondahome\Library\include /DWIN32 /D_WINDOWS  /O2 /Ob2 /DNDEBUG -MD /Oy /GR- /EHs-c- -std:c++17 /showIncludes /FoCMakeFiles\dartvm3.5.4_android_arm64.dir\runtime\vm\dart_api_state.cc.obj /FdCMakeFiles\dartvm3.5.4_android_arm64.dir\dartvm3.5.4_android_arm64.pdb /FS -c C:\Users\cpp\Desktop\ftdcp\blutterhome\dartsdk\v3.5.4\runtime\vm\dart_api_state.cc

E:\MS2019\IDE\VC\Tools\MSVC\14.29.30133\include\xkeycheck.h(53): warning C4005: 'bool': macro redefinition
E:\anacondahome\Library\include\stdbool.h(9): note: see previous definition of 'bool'
E:\MS2019\IDE\VC\Tools\MSVC\14.29.30133\include\xkeycheck.h(55): fatal error C1189: #error:  The C++ Standard Library forbids macroizing the keyword "bool". Enable warning C4005 to find the forbidden define.
[8/202] Building CXX object CMakeFiles\dartvm3.5.4_android_arm64.dir\runtime\vm\bootstrap_natives.cc.obj

> FAILED: CMakeFiles/dartvm3.5.4_android_arm64.dir/runtime/vm/bootstrap_natives.cc.obj
E:\MS2019\IDE\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe  /nologo /TP -DDART_COMPRESSED_POINTERS -DDART_PRECOMPILED_RUNTIME -DDART_TARGET_OS_ANDROID -DDART_TARGET_OS_WINDOWS_UWP -DEXCLUDE_CFE_AND_KERNEL_PLATFORM -DNDEBUG -DPRODUCT -DTARGET_ARCH_ARM64 -DU_USING_ICU_NAMESPACE=0 -D_HAS_EXCEPTIONS=0 -IC:\Users\cpp\Desktop\ftdcp\blutterhome\dartsdk\v3.5.4\runtime -IE:\anacondahome\Library\include /DWIN32 /D_WINDOWS  /O2 /Ob2 /DNDEBUG -MD /Oy /GR- /EHs-c- -std:c++17 /showIncludes /FoCMakeFiles\dartvm3.5.4_android_arm64.dir\runtime\vm\bootstrap_natives.cc.obj /FdCMakeFiles\dartvm3.5.4_android_arm64.dir\dartvm3.5.4_android_arm64.pdb /FS -c C:\Users\cpp\Desktop\ftdcp\blutterhome\dartsdk\v3.5.4\runtime\vm\bootstrap_natives.cc

E:\MS2019\IDE\VC\Tools\MSVC\14.29.30133\include\xkeycheck.h(53): warning C4005: 'bool': macro redefinition
E:\anacondahome\Library\include\stdbool.h(9): note: see previous definition of 'bool'
E:\MS2019\IDE\VC\Tools\MSVC\14.29.30133\include\xkeycheck.h(55): fatal error C1189: #error:  The C++ Standard Library forbids macroizing the keyword "bool". Enable warning C4005 to find the forbidden define.
[14/202] Building CXX object CMakeFiles\dartvm3.5.4_android_arm64.dir\runtime\vm\isolate.cc.obj
ninja: build stopped: subcommand failed.

**Comment by Deaseyy** [comment]
同样的问题

**Comment by debuggerfool** [comment]
> 同样的问题

I have already solved it

**Comment by lingdu57** [comment]
@debuggerfool  如何解决的?是不是版本问题?

**Comment by xiaogui824** [comment]
How did you solve it? I also encountered this problem recently and didn't solve it.

**Comment by worawit** [comment]
Close because debuggerfool said solved it
