### ISSUE TITLE
Decompiling from Dart version 2.8.3 fails (is it too old to be supported?)

### ISSUE THREAD

**Issue by magicus** [worawit/blutter#118]
I'm running into a lot of problems trying to decompile an app made by Dart 2.8.3. Is this supposed to work, or is it hopelessly old and I better just give up?

I got around some errors from pch.h including non-existing files, but I keep running into compilation errors, trying to work around them, and it feels like things are mostly just breaking down.

I can give more details about the errors, but I won't spend the effort unless I know this is relevant.

**Comment by worawit** [comment]
Dart 2.8 is too old. Need a lot of changes to make it work. I have no plan to support it
