### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by MrSean666** [worawit/blutter#2]
有没有Windows环境下的配置教程

**Comment by worawit** [comment]
It is in README.md
Basically Visual Studio C++ with cmake and python

**Comment by MrSean666** [comment]
> 它基本上是Visual Studio C++README.md 与cmake和python

有没有更详细的配置教程 一直跑不起来这个项目

**Comment by VicoErv** [comment]
I managed to make it work by installing this
![image](https://github.com/worawit/blutter/assets/26959883/d6f60b02-e9bc-44ee-b855-a801648cb346)

**Comment by worawit** [comment]
Nah. My installation has no Clang and it works

**Comment by coderjingluo** [comment]
> Nah. My installation has no Clang and it works

What version of ubuntu are you using?

**Comment by coderjingluo** [comment]
> Nah. My installation has no Clang and it works

Can you see what effect you can achieve by using this tool? It is best to provide the files output by using this tool

**Comment by MrSean666** [comment]
Dart version: 3.0.5, Snapshot: 90b56a561f70cd55e972cb49b79b3d8b, Target: android arm64
CMake Error at CMakeLists.txt:10 (message):
  Only 64-bit compiler here


-- Configuring incomplete, errors occurred!

**Comment by worawit** [comment]
Use "x64 Native Tools Command Prompt". You are using x86 (32 bit) tools.
You might have to delete the "build" folder. IIRC, CMake does not update build tool on existed build folder.

**Comment by MrSean666** [comment]
大佬的项目非常棒! 希望能支持解析32位版本的so文件, frida js脚本最好能兼容下es5语法.

**Comment by Chendp124** [comment]
Dart version: 3.0.1, Snapshot: aa64af18e7d086041ac127cc4bc50c5e, Target: android arm64
ver：3.0.1 arch：arm64 os_name：android
Traceback (most recent call last):
  File "blutter.py", line 140, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln)
  File "blutter.py", line 102, in main
    fetch_and_build(dart_version, arch, os_name)
  File "D:\PyCharm2022.2.3\blutter\dartvm_fetch_build.py", line 72, in fetch_and_build
    outdir = checkout_dart(ver)
  File "D:\PyCharm2022.2.3\blutter\dartvm_fetch_build.py", line 25, in checkout_dart
    subprocess.run([GIT_CMD, '-c', 'advice.detachedHead=false', 'clone', '-b', ver, '--depth', '1', '--filter=blob:none', '--sparse', '--progress', DART_GIT_URL, clonedir], check=True)
  File "D:\Python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

环境配置了提示找不到文件
