### ISSUE TITLE
Get exception with `TestType is not Type`

### ISSUE THREAD

**Issue by Yixi** [worawit/blutter#32]
![image](https://github.com/worawit/blutter/assets/1411722/905e92cf-6579-4655-94b9-bbe4448d2ab5)

any help?

**Comment by worawit** [comment]
I changed the code to print only an error and continue a program in a latest commit.

The bug is still there and might be found at other places.

**Comment by Yixi** [comment]
![image](https://github.com/worawit/blutter/assets/1411722/761dedaf-f797-449f-afbf-47bc22321b7f)
hmmm.. 
Still can't work.

**Comment by Yixi** [comment]
Worked!, amazing job!
