### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by CHINA-china** [worawit/blutter#34]
I encountered the following issues while using it, and I hope to receive your answers. Thank you
```
C:\Users\admin\Desktop\blutter-main>python blutter.py C:\Users\admin\Desktop\2 C:\Users\admin\Desktop\2
Traceback (most recent call last):
  File "blutter.py", line 168, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "blutter.py", line 100, in main
    dart_version, snapshot_hash, flags, arch, os_name = extract_dart_info(libapp_file, libflutter_file)
  File "C:\Users\admin\Desktop\blutter-main\extract_dart_info.py", line 110, in extract_dart_info
    engine_ids, dart_version, arch, os_name = extract_libflutter_info(libflutter_file)
  File "C:\Users\admin\Desktop\blutter-main\extract_dart_info.py", line 44, in extract_libflutter_info
    assert len(sha_hashes) == 2
AssertionError
```
![21387859577_129654793076_A9D23446-3D6A-4e76-ADEB-0802FC146CE6](https://github.com/worawit/blutter/assets/92798047/2e063d46-ce4f-4474-88b5-21b25e890ac2)

**Comment by worawit** [comment]
It might be a custom libflutter.so. Normal libflutter should have no this error.

Can you give me a libflutter.so?

**Comment by CHINA-china** [comment]
[2.zip](https://github.com/worawit/blutter/files/14022583/2.zip)
Thank you for your reply. I have already packaged and sent the SO file.

**Comment by CHINA-china** [comment]
Thank you for your reply. I have already packaged and sent the SO file

**Comment by CHINA-china** [comment]
Can you tell me the reason and how I can solve it

**Comment by worawit** [comment]
It is fixed in latest commit. Just do "git pull" and run the command again.
