### ISSUE TITLE
Ask for advice humbly

### ISSUE THREAD

**Issue by BrilliantFish** [worawit/blutter#35]
- How did the authors know about Dart's Object Pool structure?
- Is there any relevant information I can look at? Because I am very curious about this part of the technology

**Comment by BrilliantFish** [comment]
@worawit

**Comment by worawit** [comment]
Most info are from reading Dart VM source code. There is no document for internal Dart objects.
This project has no parser for reading Dart object or snapshot. It uses Dart internal library to access information. So basic information can be extracted without knowing internal object structure.
