### ISSUE TITLE
rename error

### ISSUE THREAD

**Issue by anonyein** [worawit/blutter#41]
when run the python script "addNames.py" on IDA, some error log below
4B764C: can't rename byte as 'get$get_rx$src$rx_types$rx_types_::RxNumExt.>_4b764c' because it contains a bad character '>'.
7D1B64: can't rename byte as 'gg$global_service$g_webrtc_proxy_server_::_extension#0.toDCPacket_7d1b64' because it contains a bad character '#'.

illegal rename, can it be fixed?

**Comment by worawit** [comment]
Fixed in latest commit
