### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by RickyCong** [worawit/blutter#47]
Dart version: 2.18.4, Snapshot: b0e899ec5a90e4661501f0b69e9dd70f, Target: android arm64
flags: product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64-sysv compressed-pointers no-null-safety
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /home/manjaro/Pictures/pojieFramework/blutter/build/blutter_dartvm2.18.4_android_arm64
[1/2] Building CXX object CMakeFiles/blutter_dartvm2.18.4_android_arm64.dir/src/CodeAnalyzer_arm64.cpp.o
FAILED: CMakeFiles/blutter_dartvm2.18.4_android_arm64.dir/src/CodeAnalyzer_arm64.cpp.o 
/usr/bin/c++ -DDART_COMPRESSED_POINTERS -DDART_PRECOMPILED_RUNTIME -DDART_TARGET_OS_ANDROID -DDART_TARGET_OS_WINDOWS_UWP -DEXCLUDE_CFE_AND_KERNEL_PLATFORM -DFRIDA_TEMPLATE_DIR=\"/home/manjaro/Pictures/pojieFramework/blutter/scripts\" -DHAS_SHARED_CLASS_TABLE -DHAS_TYPE_REF -DNDEBUG -DOLD_MAP_SET_NAME -DPRODUCT -DTARGET_ARCH_ARM64 -DU_USING_ICU_NAMESPACE=0 -D_HAS_EXCEPTIONS=0 -I/usr/include/capstone -isystem /home/manjaro/Pictures/pojieFramework/blutter/packages/include/dartvm2.18.4 -O3 -DNDEBUG -std=c++20 -O3 -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -fno-omit-frame-pointer -Winvalid-pch -include /home/manjaro/Pictures/pojieFramework/blutter/build/blutter_dartvm2.18.4_android_arm64/CMakeFiles/blutter_dartvm2.18.4_android_arm64.dir/cmake_pch.hxx -MD -MT CMakeFiles/blutter_dartvm2.18.4_android_arm64.dir/src/CodeAnalyzer_arm64.cpp.o -MF CMakeFiles/blutter_dartvm2.18.4_android_arm64.dir/src/CodeAnalyzer_arm64.cpp.o.d -o CMakeFiles/blutter_dartvm2.18.4_android_arm64.dir/src/CodeAnalyzer_arm64.cpp.o -c /home/manjaro/Pictures/pojieFramework/blutter/blutter/src/CodeAnalyzer_arm64.cpp
/home/manjaro/Pictures/pojieFramework/blutter/blutter/src/CodeAnalyzer_arm64.cpp: In member function ‘std::unique_ptr<CallLeafRuntimeInstr> FunctionAnalyzer::processCallLeafRuntime(AsmIterator&)’:
/home/manjaro/Pictures/pojieFramework/blutter/blutter/src/CodeAnalyzer_arm64.cpp:578:173: 错误：‘PropagateError_entry_point_offset’不是‘dart::Thread’的成员
  578 |                 (insn.id() == ARM64_INS_LDR && GetThreadLeafFunction(insn.ops(1).mem.disp) && insn.ops(1).mem.base != CSREG_DART_PP && insn.ops(1).mem.disp > dart::Thread::PropagateError_entry_point_offset()))
      |                                                                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/manjaro/Pictures/pojieFramework/blutter/blutter.py", line 168, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln, args.no_analysis)
  File "/home/manjaro/Pictures/pojieFramework/blutter/blutter.py", line 149, in main
    cmake_blutter(blutter_name, dartlib_name, name_suffix, macros)
  File "/home/manjaro/Pictures/pojieFramework/blutter/blutter.py", line 92, in cmake_blutter
    subprocess.run([NINJA_CMD], cwd=builddir, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja']' returned non-zero exit status 1.

**Comment by cryptax** [comment]
Same error for me.

**Comment by worawit** [comment]
should be fixed in latest commit

**Comment by RickyCong** [comment]
I pulled the code again and then succeeded with --rebuild.

> should be fixed in latest commit
