### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by sirendz124** [worawit/blutter#5]
Traceback (most recent call last):
  File "D:\PyCharm2022.2.3\blutter\scripts\dartvm_create_srclist.py", line 72, in <module>
    srcs = get_default_src_files(os.path.join(BASEDIR, 'lib', lib+'_sources.gni'))
  File "D:\PyCharm2022.2.3\blutter\scripts\dartvm_create_srclist.py", line 27, in get_default_src_files
    objs = extract_sources(gni_file)
  File "D:\PyCharm2022.2.3\blutter\scripts\dartvm_create_srclist.py", line 9, in extract_sources
    with open(gni_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '.\\lib\\async_sources.gni'
Traceback (most recent call last):
  File "blutter.py", line 140, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln)
  File "blutter.py", line 102, in main
    fetch_and_build(dart_version, arch, os_name)
  File "D:\PyCharm2022.2.3\blutter\dartvm_fetch_build.py", line 75, in fetch_and_build
    cmake_dart(ver, arch, os_name, outdir)
  File "D:\PyCharm2022.2.3\blutter\dartvm_fetch_build.py", line 60, in cmake_dart
    subprocess.run([sys.executable, CREATE_SRCLIST_FILE, target_dir], check=True)
  File "D:\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\Python38\\python.exe', 'D:\\PyCharm2022.2.3\\blutter\\scripts\\dartvm_create_srclist.py', 'D:\\PyCharm2022.2.3\\blutter\\dartsdk\\v3.0.5']' returned non-zero exit status 1.

**Comment by worawit** [comment]
From the error, I guess it because git cloning dart sdk failed in previous run.

Try pull the latest commit and try again. Now, I check cloning completion instead of check the existence of dart directory.

**Comment by sirendz124** [comment]
Using the latest test or reporting an error

`Dart version: 3.0.1, Snapshot: aa64af18e7d086041ac127cc4bc50c5e, Target: android arm64
Traceback (most recent call last):
  File "blutter.py", line 140, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln)
  File "blutter.py", line 102, in main
    fetch_and_build(dart_version, arch, os_name)
  File "D:\PyCharm2022.2.3\blutter\dartvm_fetch_build.py", line 92, in fetch_and_build
    outdir = checkout_dart(ver)
  File "D:\PyCharm2022.2.3\blutter\dartvm_fetch_build.py", line 40, in checkout_dart
    subprocess.run(
  File "D:\Python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。`

**Comment by sirendz124** [comment]
> From the error, I guess it because git cloning dart sdk failed in previous run.
> 
> Try pull the latest commit and try again. Now, I check cloning completion instead of check the existence of dart directory.

Using the latest test or reporting an error

**Comment by worawit** [comment]
Do you have properly environment setup? I think the line of error is executing "git" command but cannot find it.

On windows, you need python, git, Visual Studio with C++ compiler and CMake. Then, you have to start in dev command prompt.

**Comment by sirendz124** [comment]
> 您是否有正确的环境设置？我认为错误行是执行“git”命令但找不到它。
> 
> 在 Windows 上，您需要 python、git、带有 C++ 编译器的 Visual Studio 和 CMake。然后，您必须在 dev 命令提示符下启动。

What is your CMake version。
I pulled down the project again and found new errors after building a new environment。

```
Dart version: 3.0.1, Snapshot: aa64af18e7d086041ac127cc4bc50c5e, Target: android arm64
Cloning into 'D:\PyCharm2022.2.3\blutter\dartsdk\v3.0.1'...
remote: Enumerating objects: 2444, done.
remote: Counting objects: 100% (2444/2444), done.
remote: Compressing objects: 100% (2003/2003), done.
Receiving objects: 100% (2444/2444), 1.46 MiB | 7.14 MiB/s, done.d 0

Resolving deltas: 100% (77/77), done.
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (22/22), done.
Receiving objects:  65% (15/23)
Receiving objects: 100% (23/23), 126.89 KiB | 2.88 MiB/s, done.
Updating files: 100% (23/23), done.
remote: Enumerating objects: 3534, done.
remote: Counting objects: 100% (3534/3534), done.
remote: Compressing objects: 100% (2472/2472), done.
remote: Total 3534 (delta 1195), reused 2017 (delta 1020), pack-reused 0
Receiving objects: 100% (3534/3534), 8.08 MiB | 11.28 MiB/s, done.
Resolving deltas: 100% (1195/1195), done.
Updating files: 100% (4017/4017), done.
CMake Error at CMakeLists.txt:9 (if):
  if given arguments:

    "STREQUAL" "4"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "blutter.py", line 138, in <module>
    main(args.indir, args.outdir, args.rebuild, args.vs_sln)
  File "blutter.py", line 101, in main
    fetch_and_build(dart_version, arch, os_name)
  File "D:\PyCharm2022.2.3\blutter\dartvm_fetch_build.py", line 83, in fetch_and_build
    cmake_dart(ver, arch, os_name, outdir)
  File "D:\PyCharm2022.2.3\blutter\dartvm_fetch_build.py", line 75, in cmake_dart
    subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={os_name}', f'-DTARGET_ARCH={arch}', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE'], cwd=target_dir, check=True)
  File "D:\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-B', 'D:\\PyCharm2022.2.3\\blutter\\build\\dartvm3.0.1_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
```

**Comment by worawit** [comment]
On Windows, you have to run this tool from "x64 Native Tools Command Prompt" (see README.md).
This prompt will set environments for using MS Build tools (including cl, cmake and ninja from Visual Studio). You don't have to install standalone CMake on your machine.
If you do not want to install Visual Studio, you can run this tool on Debian sid/trixie. It can be run in container/VM/WSL.

**Comment by sirendz124** [comment]
> On Windows, you have to run this tool from "x64 Native Tools Command Prompt" (see README.md). This prompt will set environments for using MS Build tools (including cl, cmake and ninja from Visual Studio). You don't have to install standalone CMake on your machine. If you do not want to install Visual Studio, you can run this tool on Debian sid/trixie. It can be run in container/VM/WSL.
I am running tools on x64 Native Tools Command Prompt.
Dart version: 3.0.5, Snapshot: 90b56a561f70cd55e972cb49b79b3d8b, Target: android arm64  This version can run normally
Dart version: 3.0.1, Snapshot: aa64af18e7d086041ac127cc4bc50c5e, Target: android arm64  Only then will I report this error as feedback

**Comment by worawit** [comment]
The error line is for checking 64 bit compiler. An error message shows that cmake cannot detect compiler.

There might be something wrong from previous cmake run and cached. You can try deleting "D:\\PyCharm2022.2.3\\blutter\\build\\dartvm3.0.1_android_arm64" and try again.

**Comment by sirendz124** [comment]
> The error line is for checking 64 bit compiler. An error message shows that cmake cannot detect compiler.
> 
> There might be something wrong from previous cmake run and cached. You can try deleting "D:\PyCharm2022.2.3\blutter\build\dartvm3.0.1_android_arm64" and try again.

I resolved this issue after deleting it. Thank you very much
