### ISSUE TITLE
Dart Dev: `3.0.0-30.dev` - `3.0.0-51.dev`

### ISSUE THREAD

**Issue by AbhiTheModder** [worawit/blutter#64]
Hi @worawit ,
Dart in it's dev version from `3.0.0-30.dev` to `3.0.0-51.dev` had used `field_names()` instead of `GetFieldNames(thread)`.
I modified [blutter/src/DartTypes](https://github.com/AbhiTheModder/blutter-termux/blob/3.0.0-XX.0.dev/blutter/src/DartTypes.cpp#L202) which works, but I can't think of a way to make it such it works as a detection if `GetFieldNames` isn't available it should try using `field_names`, unless we add an env var through python and check for dart version and apply conditionals, but that'll change structure of blutter a little so I haven't worked on that.

If it is possible without those please try to implement it. ❤️

Thanks

**Comment by worawit** [comment]
I think it is not worth to make it work for these versions. Very few application development use these dev versions. Even someone use it, I believe they will upgrade their flutter in a new application version.

**Comment by AbhiTheModder** [comment]
Got it, thanks
