### ISSUE TITLE
Unlink of file

### ISSUE THREAD

**Issue by dsr2022** [worawit/blutter#86]
Dart version: 3.3.3, Snapshot: ee1eb666c76a5cb7746faf39d0b97547, Target: android arm64
flags: product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-tsan no-asserts arm64 android compressed-pointers null-safety
Cloning into 'E:\blutter\dartsdk\v3.3.3'...
remote: Enumerating objects: 2385, done.
remote: Counting objects: 100% (2385/2385), done.
remote: Compressing objects: 100% (1936/1936), done.
remote: Total 2385 (delta 49), reused 1420 (delta 40), pack-reused 0 eceiving objects:  98% (2338/2385), 932.
Receiving objects: 100% (2385/2385), 1.35 MiB | 1.87 MiB/s, done.

********
********
********

remote: Counting objects: 100% (5393/5393), done.
remote: Compressing objects: 100% (350/350), done.
remote: Total 104107 (delta 5246), reused 5043 (delta 5043), pack-reused 98714
Receiving objects: 100% (104107/104107), 12.29 MiB | 3.86 MiB/s, done.
Resolving deltas: 100% (66695/66695), done.
fatal: unable to access 'https://github.com/dart-lang/sdk.git/': OpenSSL SSL_read: error:14095126:SSL routines:ssl3_read_n:unexpected eof while reading, errno 0
Unlink of file 'E:\blutter\dartsdk\v3.3.3/.git/objects/pack/pack-00d947c80237a5e45089087326207e49f578f9fa.idx' failed. Should I try again? (y/n) y
Unlink of file 'E:\blutter\dartsdk\v3.3.3/.git/objects/pack/pack-00d947c80237a5e45089087326207e49f578f9fa.idx' failed. Should I try again? (y/n) y
Unlink of file 'E:\blutter\dartsdk\v3.3.3/.git/objects/pack/pack-00d947c80237a5e45089087326207e49f578f9fa.idx' failed. Should I try again? (y/n) y

I have tried several times and it has always been like this. Is there any solution?

**Comment by worawit** [comment]
maybe your git version is too old

**Comment by dsr2022** [comment]
Yes, it was indeed due to Git during the later check. I tried running it on Linux and found that some versions that were too low would cause script errors when running

**Comment by dsr2022** [comment]
My Git version is 2.26.0. I checked the network connection and found no issues. However, I have used it several times on Windows and have encountered errors

**Comment by AbhiTheModder** [comment]
> My Git version is 2.26.0. I checked the network connection and found no issues. However, I have used it several times on Windows and have encountered errors

The issue seems to be with the OpenSSL library that your Git is utilizing. I recommend performing a fresh installation of 'Git for Windows' and selecting Git's own OpenSSL library to be used during the installation process.

**Comment by dsr2022** [comment]
I tried to add a proxy to Git, did not encounter this error. I ran "python3 blutter. py   source_dir   out_dir" on Windows for over half an hour and still haven't finished. I used more than 10 GB of data. Is this normal?

**Comment by AbhiTheModder** [comment]
> I tried to add a proxy to Git, did not encounter this error. I ran "python3 blutter. py source_dir out_dir" on Windows for over half an hour and still haven't finished. I used more than 10 GB of data. Is this normal?

Under normal circumstances, the processes of fetching, pulling, building, and analyzing Dart versions do take a considerable amount of time, so the observed time gap is expected. Regarding data usage, it typically consumes several gigabytes, though it generally does not reach 10GB. The use of a proxy may also contribute to this data usage in your case I assume.

**Comment by dsr2022** [comment]
Is it because my file liapp.so is too large? The file liapp.so has 16MB

**Comment by dsr2022** [comment]
Finally, I discovered the problem. It was indeed due to the low Git version that . I tried upgrading the Git version to the latest 2.46.0 to solve this problem. Thank you
