### ISSUE TITLE
Migration From Intel Mac to M3 Mac, build blutter_dartvm3.3.4_android_arm64 error. any idea to solve this?

### ISSUE THREAD

**Issue by OwenSu** [worawit/blutter#87]
➜  blutter python blutter.py ./lib/arm64-v8a output
Dart version: 3.3.4, Snapshot: ee1eb666c76a5cb7746faf39d0b97547, Target: android arm64
flags: product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-tsan no-asserts arm64 android compressed-pointers null-safety
-- Configuring done (0.1s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/newand/work/blutter/build/blutter_dartvm3.3.4_android_arm64
[1/1] Linking CXX executable blutter_dartvm3.3.4_android_arm64
FAILED: blutter_dartvm3.3.4_android_arm64
: && /opt/homebrew/opt/llvm@16/bin/clang++ -O3 -DNDEBUG -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -fexperimental-library -L/opt/homebrew/opt/llvm@16/bin/../lib/c++ -dead_strip CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/CodeAnalyzer.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/CodeAnalyzer_arm64.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/DartApp.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/DartClass.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/DartDumper.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/DartField.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/DartFunction.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/DartLibrary.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/DartLoader.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/DartStub.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/DartThreadInfo.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/DartTypes.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/Disassembler.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/Disassembler_arm64.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/ElfHelper.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/FridaWriter.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/Util.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/VarValue.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/il.cpp.o CMakeFiles/blutter_dartvm3.3.4_android_arm64.dir/src/main.cpp.o -o blutter_dartvm3.3.4_android_arm64 -L/opt/homebrew/Cellar/capstone/5.0.1/lib -Wl,-rpath,/opt/homebrew/Cellar/capstone/5.0.1/lib  /Users/newand/work/blutter/packages/lib/libdartvm3.3.4_android_arm64.a  -lcapstone  -ldl  -lpthread  /opt/homebrew/opt/icu4c/lib/libicuuc.dylib && :
ld: warning: ignoring file '/opt/homebrew/Cellar/icu4c/74.2/lib/libicuuc.74.2.dylib': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/capstone/5.0.1/lib/libcapstone.5.dylib': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/llvm@16/16.0.6_1/lib/c++/libc++.1.0.dylib': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/llvm@16/16.0.6_1/lib/c++/libc++experimental.a[3](format.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/llvm@16/16.0.6_1/lib/c++/libc++experimental.a[2](memory_resource.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
Undefined symbols for architecture x86_64:

**Comment by OwenSu** [comment]
os version : macOs Sonoma 14.5

**Comment by worawit** [comment]
delete `packages` and `build` directories.

**Comment by OwenSu** [comment]
I've solved this problem. Because my python is migration from inter mac, its arch is x86_64, after reinstall python, everything is fine.
