### ISSUE TITLE
IDA Script contains bad characters in `idaapi.set_name` function

### ISSUE THREAD

**Issue by zhangz1han** [worawit/blutter#93]
IDA does not support the `#` and `|` characters in function names

#41 mentions that this issue has been fixed, but it still exists

![屏幕截图 2024-08-11 145519](https://github.com/user-attachments/assets/8ec5a671-65e7-4fc4-991d-a7f950c637ea)

![屏幕截图 2024-08-11 145619](https://github.com/user-attachments/assets/328b7b80-cbc9-45b3-b17c-d45a87b00e08)

![image](https://github.com/user-attachments/assets/91424129-ffb8-437a-8bd1-b3dc7f628bc6)

![image](https://github.com/user-attachments/assets/cbe49531-e210-420f-b4e3-dde91a13d4cd)

**Comment by AbhiTheModder** [comment]
In `DartDumper.cpp`, the issue can be addressed with the following code:
```cpp
    std::replace(fnName.begin(), fnName.end(), '#', '@');
    std::replace(fnName.begin(), fnName.end(), '|_', '_');
    std::replace(fnName.begin(), fnName.end(), '|', '_');
```

There might be a better way to approach this.

**Comment by AbhiTheModder** [comment]
> > In `DartDumper.cpp`, the issue may be resolved using the code below:
> 
> Sorry I'm not familiar with C++ code. Can you tell me where these codes should be placed in the file?

at Line [#L34](https://github.com/worawit/blutter/blob/main/blutter/src/DartDumper.cpp#L34):
![image](https://github.com/user-attachments/assets/5a51f799-0bb9-4630-9869-2d8cb65a9f5f)

**Comment by AbhiTheModder** [comment]
@zhangzih4n thanks for the error output could you give the `libapp.so` file, if possible, will do a quick test and suggest you with the changes

**Comment by AbhiTheModder** [comment]
> > @zhangzih4n thanks for the error output could you give the `libapp.so` file, if possible, will do a quick test and suggest you with the changes
> 
> It runs fine without adding these three lines of code, I guess this error is not caused by `libapp.so`

I had asked for checking from side in any case no need, identified the location was wrong you should modify at [#L116](https://github.com/worawit/blutter/blob/main/blutter/src/DartDumper.cpp#L116)
![image](https://github.com/user-attachments/assets/84c843c1-a7c2-4a71-8a9d-e42f6cc53e6b)


Should be fixed now

**Comment by AbhiTheModder** [comment]
> > @zhangzih4n thanks for the error output could you give the `libapp.so` file, if possible, will do a quick test and suggest you with the changes
> 
> It runs fine without adding these three lines of code, I guess this error is not caused by `libapp.so`
> 
> I tried two Flutter Apps and both got this error
> 
> [libapp.zip](https://github.com/user-attachments/files/16579776/libapp.zip)

Thanks for the file, at the same line where i instructed you add these lines:
```cpp
	if (fnName.starts_with("#")) {
		fnName.replace(0, 1, "@");
	}

	for (size_t pos = 0; ; pos += 1) {
		pos = fnName.find("|_", pos);
		if (pos == std::string::npos) break;
		fnName.replace(pos, 2, "_");
	}
```

Like this:
![image](https://github.com/user-attachments/assets/28547b7b-03f7-44bc-aa75-eee2e383309e)
